# Generated by Django 2.1.1 on 2018-10-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('Stablished_date', models.CharField(max_length=100)),
            ],
        ),
    ]
