# Generated by Django 2.1.1 on 2018-10-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Relation', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50)),
                ('age', models.IntegerField(max_length=100)),
                ('phone', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
