# Generated by Django 2.1.1 on 2018-10-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='age',
            field=models.IntegerField(),
        ),
    ]
