# Generated by Django 2.1.1 on 2018-10-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guard',
            field=models.OneToOneField(on_delete=None, to='student.Guardian'),
        ),
    ]
