# Generated by Django 2.1.1 on 2018-10-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Area', models.CharField(max_length=100)),
                ('Population', models.CharField(max_length=100)),
            ],
        ),
    ]
